services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    volumes:
      - sql-data-2017:/var/opt/mssql

  api:
    build:
      context: ./backend
      dockerfile: InnomateApp.API/Dockerfile
    container_name: ${API_CONTAINER_NAME}
    ports:
      - "${API_PORT}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SmartOps;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;MultipleActiveResultSets=True;Encrypt=False;
    depends_on:
      - sqlserver

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: ${UI_CONTAINER_NAME}
    ports:
      - "${UI_PORT}:80"
    depends_on:
      - api

volumes:
  sql-data-2017:
